# Generated by Django 5.2.14 on 2026-05-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('last_fetched', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
