# Generated by Django 5.2.14 on 2026-06-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_trend'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_hash', models.CharField(max_length=64, unique=True)),
                ('topic', models.CharField(max_length=255)),
                ('context', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('platforms', models.CharField(default='LinkedIn, Instagram, X', max_length=100)),
                ('tone', models.CharField(blank=True, max_length=60)),
                ('audience', models.CharField(blank=True, max_length=120)),
                ('length', models.CharField(blank=True, max_length=40)),
                ('emoji_style', models.CharField(blank=True, max_length=40)),
                ('cta', models.CharField(blank=True, max_length=120)),
                ('hashtags', models.CharField(blank=True, max_length=120)),
                ('generated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
